# -*- coding: utf-8 -*-
"""Control calse 15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/198yvKAYQBDJVLQ3SOb2jWySLOWgS60Tf
"""

import streamlit as st
import pandas as pd
import requests
import matplotlib.pyplot as plt

# Definición de función para obtener datos de una API con una URL proporcionada
def obtener_datos_api(api_url):
    """Función que realiza la petición a la API y devuelve un DataFrame."""
    response = requests.get(api_url)
    if response.status_code == 200:
        data = response.json()
        return pd.DataFrame(data)
    else:
        st.error('Error al obtener los datos de la API')
        return None

# Interfaz para ingresar la URL de la API
st.title('Aplicación Web: Cargar datos desde una API REST')
api_url = st.text_input('Introduce la URL de la API REST:', 'https://jsonplaceholder.typicode.com/posts')

# Llamar la función para obtener los datos
if api_url:
    df = obtener_datos_api(api_url)
    # Si hay datos, mostrar el DataFrame y permitir manipulación
    if df is not None:
        # Mostrar los primeros 5 registros
        st.write('Datos obtenidos de la API:')
        st.write(df.head())

        # Seleccionar columnas para visualizar
        columnas = st.multiselect('Selecciona las columnas a visualizar', df.columns.tolist(), default=df.columns.tolist())
        df_seleccionado = df[columnas]
        st.write('Datos seleccionados:')
        st.write(df_seleccionado)

        # Filtrar por ID
        id_filtro = st.slider('Filtrar por ID (entre 1 y 100)', 1, 100, 50)
        df_filtrado = df[df['id'] <= id_filtro]
        st.write(f'Mostrando datos donde ID <= {id_filtro}:')
        st.write(df_filtrado)

        # Gráfico de barras de User ID
        fig, ax = plt.subplots()
        df['userId'].value_counts().sort_index().plot(kind='bar', ax=ax)
        ax.set_title('Conteo de User ID')
        ax.set_xlabel('User ID')
        ax.set_ylabel('Frecuencia')
        st.pyplot(fig)